### ISSUE TITLE
Abstract Layout

### ISSUE THREAD

**Issue by amcdnl** [upsetjs/chartjs-chart-venn#1]
In the new D3, they have extracted the layout/math portions into separate libraries. 

I would love to use this library in https://reaviz.io but its so tightly coupled to ChartJS I'm not sure its possible w/o major mods.

**Comment by sgratzl** [comment]
this library is partly based on https://github.com/upsetjs/venn.js and the venn diagram feature of https://github.com/upsetjs/upsetjs

**Comment by amcdnl** [comment]
In the venn.js library - is there a Euler layout? The page says but I can't seem to figure out how to use it based on the code.

**Comment by sgratzl** [comment]
the whole venn.js library is just creating proportional euler diagrams where the overlaps correspond to the overlap in the data

**Comment by amcdnl** [comment]
@sgratzl - Shot you an email but this is what I'm working on here - https://github.com/reaviz/reaviz/compare/euler#diff-58874db3bcd8d8718b01be0a5211ee22R72
