### ISSUE TITLE
How can select one zone in your wenn implementation?

### ISSUE THREAD

**Issue by mmm2006** [upsetjs/chartjs-chart-venn#16]
HI, 

I just study your venn implementation. It is great. I don't know how to select one zone just like your implementaion.

In benfred implementation, it don't support this.  And when mouse hover, related zone is highlighted. Is this implemented by chart.js, right? 

![image](https://user-images.githubusercontent.com/313394/187325960-dd05018e-7330-470b-ba97-a9233ee58aca.png)

benfred:
https://github.com/benfred/venn.js

Thanks.

br

wt

**Comment by sgratzl** [comment]
closing stale
