### ISSUE TITLE
Custom value

### ISSUE THREAD

**Issue by KirillAleshkin** [upsetjs/chartjs-chart-venn#25]
Hi if i can to customize me value

![image](https://user-images.githubusercontent.com/78299190/206910365-ecdfa594-a1bf-4c53-9791-677ba0fc09b3.png)

**Comment by sgratzl** [comment]
so far there are only limited styling options for the value label, not sure what you are looking for

**Comment by aryankranthi** [comment]
Hi @sgratzl ,
can we add only the names of labels,  that would be great if you help me with that?

FYI: 
<img width="411" alt="Screenshot 2023-05-10 at 8 50 51 PM" src="https://github.com/upsetjs/chartjs-chart-venn/assets/29574535/7e7bf164-cdb7-4b37-9a14-52239aa16adf">

**Comment by sgratzl** [comment]
take a look at https://upset.js.org/chartjs-chart-venn/examples/labels.html for indication on how to customize labels. The custom formatting function might be an option to change the label
