### ISSUE TITLE
Is it possible to add in React a tag and display it?

### ISSUE THREAD

**Issue by swarnas89** [upsetjs/chartjs-chart-venn#3]
.I want to get the values of set from backend and create venn diagram on select of values from dropdown.Is it possible to add a tag and give config options there?I am using reactjs.just like other barcharts and so on,I want to add a tag .Is it possible?

**Comment by sgratzl** [comment]
this repo is just a plugin for chart.js. So, you first have to be able to use chart.js in your react application and then you can use this plugin as an additional chart type
