### ISSUE TITLE
Changing model geometry

### ISSUE THREAD

**Issue by ctrlaltdel85** [upsetjs/chartjs-chart-venn#34]
I'd like to change the model geometry for 3, 4, and 5 venns to reposition the circles or change from ellipses to full circles. The arc positions in the model data seem precisely calculated and is confusing to change. How did you generate these numbers? For example, if I wanted to change the center position of a full circle, how do I update all of the intersection arcs accordingly? Thank you.

**Comment by sgratzl** [comment]
I was using geogebra to place the circles and compute their intersections. Since it a static layout that was the easiest solution
