### ISSUE TITLE
Throws error "'ChartVenn' is not defined  no-undef"

### ISSUE THREAD

**Issue by swarnas89** [upsetjs/chartjs-chart-venn#4]
Where do I need to import chartvenn?

**Comment by sgratzl** [comment]
the global variable `ChartVenn` is just defined when importing this plugin globally. If you import it in your code you have to register the elements you want manually.

**Comment by swarnas89** [comment]
Could you suggest what kind of variable is ChartVenn in the context of react?I am unable to understand that

**Comment by sgratzl** [comment]
this is a plugin for chart.js that has to be properly imported before it can be used.
