### ISSUE TITLE
Only backgroundColor option seems to work

### ISSUE THREAD

**Issue by freshyill** [upsetjs/chartjs-chart-venn#5]
I'm trying to style a chart but none of the options except `backgroundColor` seem to work. In chart.js, normally the style options would go in the `dataset`, but without that, I'm not sure where they go. Can you point me in the right direction?

I have an[ example on CodePen](https://codepen.io/freshyill/pen/oNBLYbp) that shows `backgroundColor` working, but nothing else. Any pointers would be helpful, Thank you!

```js
const chart = new Chart(ctx, {
  type: 'venn',
  data: data,
  options: {
    title: {
      display: true,
      text: 'Chart.js Venn Diagram Chart',
    },
    backgroundColor: ["#895b93", "#84cdec", 'orange', 'lime', 'fuchsia'], // These work!
    color: ['white', 'red', 'blue', 'rebeccapurple'], // These do nothing
    borderWidth: 10 // This affects only the legend
  }
});
```

**Comment by sgratzl** [comment]
should be fixed https://github.com/upsetjs/chartjs-chart-venn/releases/tag/v3.0.0-rc.6

see https://github.com/upsetjs/chartjs-chart-venn/blob/main/samples/styles.html

![image](https://user-images.githubusercontent.com/4129778/113154614-2e595e80-9206-11eb-95ae-68a0757d55bf.png)
