### ISSUE TITLE
react-chartjs wrapper for this library 

### ISSUE THREAD

**Issue by DAcodedBEAT** [upsetjs/chartjs-chart-venn#64]
It would be great if this library had a react component to integrate with https://github.com/reactchartjs/react-chartjs-2 (possibly as a small library which uses this package as a dependency)

**User story**

As a developer, I want a React component for integrating this library (upsetjs/chartjs-chart-venn) with reactchartjs/react-chartjs-2, so that I can easily utilize Venn chart functionality within my React applications currently using reactchartjs/react-chartjs-2.

**Additional context**

N/A

**Comment by sgratzl** [comment]
a minimal example is at https://codesandbox.io/p/sandbox/chartjs-react2-venn-5xkgzc?file=%2Fsrc%2FApp.tsx%3A2%2C1.
