### ISSUE TITLE
status

### ISSUE THREAD

**Issue by smile-yan-student** [upsetjs/chartjs-chart-venn#68]
How to change the status of a certain item to active

**Comment by sgratzl** [comment]
what do you mean with "status"?

**Comment by smile-yan-student** [comment]
I mean the “mode”

---- Replied Message ----
| From | Samuel ***@***.***> |
| Date | 03/25/2024 23:19 |
| To | upsetjs/chartjs-chart-venn ***@***.***> |
| Cc | passenger ***@***.***>,
Author ***@***.***> |
| Subject | Re: [upsetjs/chartjs-chart-venn] status (Issue #68) |

what do you mean with "status"?

**Comment by smile-yan-student** [comment]
I tried using the setActiveElements API to change the mode of the set, but it did not take effect in version 4.3.0 of chart. js
