### ISSUE TITLE
can not set data more than 5 rows

### ISSUE THREAD

**Issue by vongmengty** [upsetjs/chartjs-chart-venn#7]
I'm trying to add data more than 5 rows ,but unfortunately It show only 5 rows.

Example on CodePen : https://codepen.io/mengty/pen/LYzbJEJ

Anyone, Can you give me some issue please?

Thank you!

**Comment by sgratzl** [comment]
see first line in the README:

```
Chart.js module for charting venn diagrams with up to *five sets*.
```
https://github.com/upsetjs/chartjs-chart-venn/blob/6f6d14797fce5cf829abb3e42a289d90cdff1d05/README.md?plain=1#L5

this library only supports venn diagrams of size 3, 4, and 5.
